# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JiaKaoBaoDian' do
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 0.6'
end

target 'JiaKaoBaoDianTests' do

end

target 'JiaKaoBaoDianUITests' do

end

